name: Weaponist
main: com.playernguyen.weaponist.Weaponist
version: 1.0-snap
authors: [Player_Nguyen]
depends: [ProtocolLib]
commands:
  ammunition:
    usage: /ammunition
    description: Command of Weaponist
    aliases: [ammuition, ammo]
  weapon:
    usage: /weapon
    description: Command of Weaponist
    aliases: [weapon, gun, wp]